In [8]:
import pandas as pd
import numpy as np
from IPython.display import display

# ==========================================
# 1. LOAD DATASET
# ==========================================

file_path = r"C:\Users\Ritesh\OneDrive\Desktop\Celebal Excellence Intership\Shopping Analysis\Data\archive\Combined_dataset.csv"
df = pd.read_csv(file_path)

# Standardize column names
df.columns = df.columns.str.strip().str.lower()

print("DATASET LOADED SUCCESSFULLY")
print("\nColumns in dataset:")
print(df.columns.tolist())

# ==========================================
# 2. DATA EXPLORATION
# ==========================================

print("\n========== FIRST 5 ROWS ==========")
display(df.head())

print("\n========== LAST 5 ROWS ==========")
display(df.tail())

print("\n========== DATA SHAPE ==========")
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

print("\n========== DATA TYPES ==========")
print(df.dtypes)

print("\n========== DATASET INFO ==========")
df.info()

print("\n========== STATISTICAL SUMMARY ==========")
display(df.describe(include='all'))

# ==========================================
# 3. MISSING VALUES
# ==========================================

print("\n========== MISSING VALUES ==========")
print(df.isnull().sum())

# Remove completely empty rows
df = df.dropna(how='all')

# ==========================================
# 4. REMOVE DUPLICATES
# ==========================================

duplicate_count = df.duplicated().sum()
print(f"\nDuplicate Rows Found: {duplicate_count}")

if duplicate_count > 0:
    df = df.drop_duplicates()
    print("Duplicates Removed Successfully")
else:
    print("No Duplicates Found")

# ==========================================
# 5. CLEAN / CONVERT NUMERIC COLUMNS
# ==========================================

numeric_columns = ['initial_price', 'discount', 'final_price', 'rating', 'ratings_count']

for col in numeric_columns:
    if col in df.columns:
        df[col] = pd.to_numeric(
            df[col].astype(str).str.replace(r'[^0-9.\-]', '', regex=True),
            errors='coerce'
        )

# ==========================================
# 6. HANDLE MISSING VALUES
# ==========================================

# Fill numeric columns with median
num_cols = df.select_dtypes(include='number').columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

# Fill text columns with "Unknown"
text_cols = df.select_dtypes(include=['object', 'string']).columns
df[text_cols] = df[text_cols].fillna("Unknown")

print("\nMissing Values Handled Successfully")

# ==========================================
# 7. BASIC OPERATIONS
# ==========================================

# Filter rows: products with final_price > 1000
if 'final_price' in df.columns:
    expensive_products = df[df['final_price'] > 1000]
    print("\n========== FILTERED ROWS ==========")
    print(f"Products with Final Price > 1000: {len(expensive_products)}")
    display(expensive_products.head())

# Select columns
selected_cols = [col for col in ['title', 'category', 'initial_price', 'final_price', 'rating', 'ratings_count'] if col in df.columns]

if selected_cols:
    print("\n========== SELECTED COLUMNS ==========")
    display(df[selected_cols].head())

# ==========================================
# 8. DERIVED COLUMN
# ==========================================

# Assignment says total_amount = price * quantity
# This dataset does not have price and quantity columns.
# So we create a meaningful derived column instead:
# saved_amount = initial_price - final_price

if 'initial_price' in df.columns and 'final_price' in df.columns:
    df['saved_amount'] = df['initial_price'] - df['final_price']
    print("\n========== DERIVED COLUMN ==========")
    print("saved_amount = initial_price - final_price")

# ==========================================
# 9. BASIC INSIGHTS
# ==========================================

print("\n========== INSIGHTS ==========")

if 'category' in df.columns:
    print("\nTop 10 Categories:")
    print(df['category'].value_counts().head(10))

if 'final_price' in df.columns:
    print(f"\nAverage Final Price: {df['final_price'].mean():.2f}")
    print(f"Maximum Final Price: {df['final_price'].max():.2f}")

if 'rating' in df.columns:
    print(f"\nAverage Rating: {df['rating'].mean():.2f}")

# ==========================================
# 10. SAVE CLEANED DATASET
# ==========================================

output_path = r"C:\Users\Ritesh\OneDrive\Desktop\Celebal Excellence Intership\Shopping Analysis\Data\Cleaned Dataset\Cleaned_Combined_dataset_v2.csv"
df.to_csv(output_path, index=False)

print("\nCleaned Dataset Saved Successfully")
print(output_path)

# ==========================================
# 11. SUMMARY
# ==========================================

print("\n========== DATA CLEANING SUMMARY ==========")
print(f"Total Rows: {df.shape[0]}")
print(f"Total Columns: {df.shape[1]}")
print(f"Remaining Missing Values: {df.isnull().sum().sum()}")
print(f"Remaining Duplicate Rows: {df.duplicated().sum()}")
print("\nProject Completed Successfully")

DATASET LOADED SUCCESSFULLY

Columns in dataset:
['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

========== FIRST 5 ROWS ==========

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

========== LAST 5 ROWS ==========

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

========== DATA SHAPE ==========
Rows: 1000
Columns: 24

========== DATA TYPES ==========
product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

========== DATASET INFO ==========
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

========== STATISTICAL SUMMARY ==========

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
count,1.000000e+03,1000,1000,1000.0000,1000.000000,1000.00000,879.000000,1000,1000,1000,...,1000,427,699,1000,219,699,438,1000,1000,1000
unique,NaN,454,989,NaN,NaN,NaN,NaN,466,1,1000,...,808,302,301,672,219,298,22,468,159,97
top,NaN,Roadster,Women Pink Solid Top,NaN,NaN,NaN,NaN,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on IndusI...",tops
freq,NaN,30,3,NaN,NaN,NaN,NaN,25,1000,1,...,114,27,40,135,1,40,126,306,265,122
mean,1.713437e+07,NaN,NaN,3.6215,76.691000,2723.24100,53.503982,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,3.813766e+06,NaN,NaN,1.3744,241.114263,2408.69736,18.029201,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,5.868460e+05,NaN,NaN,0.0000,0.000000,249.00000,1.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1.511501e+07,NaN,NaN,3.7000,7.000000,1399.00000,44.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1.820890e+07,NaN,NaN,4.1000,17.000000,1999.00000,56.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.902737e+07,NaN,NaN,4.3000,58.000000,3299.00000,66.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2.274707e+07,NaN,NaN,5.0000,4441.000000,22199.00000,88.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

========== MISSING VALUES ==========
product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

Duplicate Rows Found: 0
No Duplicates Found

Missing Values Handled Successfully

========== FILTERED ROWS ==========
Products with Final Price > 1000: 524

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995.0,INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",Unknown,Unknown,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Unknown,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",Unknown,Unknown,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Unknown,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",Unknown,Unknown,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Unknown,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",Unknown,Unknown,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Unknown,Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown,Unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Unknown,Unknown,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

========== SELECTED COLUMNS ==========

,title,category,initial_price,final_price,rating,ratings_count
0,Lino Perros,backpacks,3995,3995.0,3.8,15
1,Tommy Hilfiger,backpacks,2899,2899.0,4.5,67
2,Lavie,backpacks,2999,2999.0,4.4,226
3,F Gear,backpacks,1675,1675.0,4.4,1052
4,MYTRIDENT,bath-robe,2899,2899.0,4.7,12

========== DERIVED COLUMN ==========
saved_amount = initial_price - final_price

========== INSIGHTS ==========

Top 10 Categories:
category
tops            122
dresses         100
shirts           97
jeans            57
sports-shoes     51
tshirts          39
earrings         34
sweaters         34
jackets          29
casual-shoes     23
Name: count, dtype: int64

Average Final Price: 1706.10
Maximum Final Price: 17995.00

Average Rating: 3.62

Cleaned Dataset Saved Successfully
C:\Users\Ritesh\OneDrive\Desktop\Celebal Excellence Intership\Shopping Analysis\Data\Cleaned Dataset\Cleaned_Combined_dataset_v2.csv

========== DATA CLEANING SUMMARY ==========
Total Rows: 1000
Total Columns: 25
Remaining Missing Values: 0
Remaining Duplicate Rows: 0

Project Completed Successfully